### ISSUE TITLE
Can’t find libressl in docker

### ISSUE THREAD

**Issue by remioukrat** [oatpp/example-libressl#1]
I have tried your sample. To run it locally I have build libressl and it works. But to run it in docker I have tried to add "apk add libressl-dev" and CMake doesn’t found libressl.

**Comment by lganzzzo** [comment]
Hey @remioukrat ,

Have you tried the Dockerfile which goes with this example - [Dockerfile](https://github.com/oatpp/example-libressl/blob/master/Dockerfile) ?

**Comment by remioukrat** [comment]
Yeah, @lganzzzo I have test it and I have this issue 
```    
By not providing "Findoatpp-libressl.cmake" in CMAKE_MODULE_PATH this
#11 0.875   project has asked CMake to find a package configuration file provided by
#11 0.875   "oatpp-libressl", but CMake did not find one.
#11 0.875
#11 0.875   Could not find a package configuration file provided by "oatpp-libressl"
#11 0.875   (requested version 1.2.0) with any of the following names:
#11 0.875
#11 0.875     oatpp-libresslConfig.cmake
#11 0.875     oatpp-libressl-config.cmake
#11 0.875
#11 0.875   Add the installation prefix of "oatpp-libressl" to CMAKE_PREFIX_PATH or set
#11 0.875   "oatpp-libressl_DIR" to a directory containing one of the above files.  If
#11 0.875   "oatpp-libressl" provides a separate development package or SDK, be sure it
#11 0.875   has been installed.
```
I can set the CMAKE_PREFIX_PATH if I have the path to oatpp-libressl but I don’t know where I can find it and I suppose that there is a better solution.

**Comment by lganzzzo** [comment]
Hey @remioukrat ,

I fixed the dockerfile for you. Please checkout the latest master and let me know if it worked for you.

Fix was here - https://github.com/oatpp/example-libressl/commit/2390d9681bb792b44772ca475bca3e374970fd09
(Actually, I've got a bit different error on my machine, but hopefully, this fix will work for you also.)

**Comment by lganzzzo** [comment]
Please note that OpenSSL [oatpp-openssl](https://github.com/oatpp/oatpp-openssl) integration is available too (since recent times).
Also, it's recommended to use OpenSSL.

**Comment by remioukrat** [comment]
Thanks, I will try with OpenSSL ;)

**Comment by lganzzzo** [comment]
Please, let me know how it goes with OpenSSL.

I'm closing this issue...
